version: "3.8"
services:
  app:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: sleep infinity
    # command: python groundskeeper/groundskeeper.py
